<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>kissanvikas_sim</name>
  <version>0.1.0</version>
  <description>KissanVikas Smart Polyhouse Digital Twin Simulation Environment (ROS 2 Jazzy &amp; Gazebo Harmonic)</description>
  <maintainer email="dev@kissanvikas.com">KissanVikas Team</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <gazebo_sim>
      <gazebo_model_path>${prefix}/models</gazebo_model_path>
    </gazebo_sim>
  </export>
</package>
